#!/bin/bash

echo "Original upload"
git add .
git commit -m "$1"
git push -u origin master

echo "Copy to TinyComicCMS.."
cp ComicDB.mwb /var/www/html/TinyComicCMS/ComicDB.mwb
cp .gitignore /var/www/html/TinyComicCMS/.gitignore
cp index.html /var/www/html/TinyComicCMS/index.html
cp LICENSE /var/www/html/TinyComicCMS/LICENSE
cp README.md /var/www/html/TinyComicCMS/README.md
cp Requirements_and_Installation.txt /var/www/html/TinyComicCMS/Requirements_and_Installation.txt
cp upload /var/www/html/TinyComicCMS/upload_from_original_dir
cp -r page/* /var/www/html/TinyComicCMS/page/*
cp -r assets/* /var/www/html/TinyComicCMS/assets/*
cp config.php /var/www/html/TinyComicCMS/page/config.php

echo "Uploading copy.."
cd /var/www/html/TinyComicCMS/
sudo ./upload "$1"

cd /var/www/html/StarForce
echo "Done."



